# Generated by Django 5.2.14 on 2026-05-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_quick_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('service_advisor', 'Service Advisor'), ('mechanic', 'Mechanic / Technician'), ('owner', 'Vehicle Owner')], default='mechanic', help_text="Determines the user's primary responsibility in the workshop.", max_length=32),
        ),
    ]
