"""
Localized strings for PDF reports and report API errors.

Workshop language is stored on the tenant (`sq` default, `en` optional).
"""
from __future__ import annotations

SUPPORTED_LANGUAGES = frozenset({"sq", "en"})


def normalize_language(code: str | None) -> str:
    if not code:
        return "sq"
    base = str(code).lower().split("-")[0]
    return base if base in SUPPORTED_LANGUAGES else "sq"


SERVICE_REPORT: dict[str, dict[str, str]] = {
    "sq": {
        "doc_title": "Raport Servisi",
        "date_label": "Data",
        "printed_label": "Printuar",
        "ref_label": "Ref",
        "status_completed": "Përfunduar",
        "section_customer_vehicle": "Klienti & Automjeti",
        "label_customer": "Klienti",
        "label_vehicle": "Automjeti",
        "label_plate": "Targa",
        "label_vin": "VIN",
        "label_mileage": "Kilometrazhi në servis",
        "label_technician": "Mekaniku",
        "section_inspection": "Inspektim Teknik 360°",
        "col_section": "Seksioni",
        "col_check": "Kontrolli",
        "col_result": "Rezultati",
        "section_work": "Puna e Kryer",
        "col_services": "Shërbimet",
        "col_parts": "Pjesët & materialet",
        "col_labor": "Puna",
        "col_qty": "Sasi",
        "col_unit": "Njësia",
        "col_total": "Totali",
        "col_hours": "Orë",
        "col_rate": "Tarifa/orë",
        "subtotal_services": "Nëntotali shërbimeve",
        "subtotal_parts": "Nëntotali pjesëve",
        "subtotal_labor": "Nëntotali punës",
        "empty_lines": "Nuk ka rreshta të regjistruar për këtë vizitë.",
        "total_services": "Shërbimet",
        "total_parts": "Pjesët & materialet",
        "total_labor": "Puna",
        "total_due": "Shuma totale",
        "section_notes": "Shënime të Teknikut",
        "sig_customer": "Nënshkrimi i klientit",
        "sig_authorized": "Autorizuar nga",
        "footer_legal": (
            "Ky dokument është dëshmi e punës së kryer në datën e përcaktuar më sipër. "
            "Ju lutemi ta ruani për historikun e servisit të automjetit tuaj."
        ),
        "footer_generated": "Gjeneruar nga Workshop360",
        "part_fallback": "Pjesë",
        "tel_prefix": "Tel",
    },
    "en": {
        "doc_title": "Service Report",
        "date_label": "Date",
        "printed_label": "Printed",
        "ref_label": "Ref",
        "status_completed": "Completed",
        "section_customer_vehicle": "Customer & Vehicle",
        "label_customer": "Customer",
        "label_vehicle": "Vehicle",
        "label_plate": "Plate",
        "label_vin": "VIN",
        "label_mileage": "Mileage at service",
        "label_technician": "Mechanic",
        "section_inspection": "360° Technical Inspection",
        "col_section": "Section",
        "col_check": "Check",
        "col_result": "Result",
        "section_work": "Work Performed",
        "col_services": "Services",
        "col_parts": "Parts & materials",
        "col_labor": "Labor",
        "col_qty": "Qty",
        "col_unit": "Unit",
        "col_total": "Total",
        "col_hours": "Hours",
        "col_rate": "Rate/hr",
        "subtotal_services": "Services subtotal",
        "subtotal_parts": "Parts subtotal",
        "subtotal_labor": "Labor subtotal",
        "empty_lines": "No line items recorded for this visit.",
        "total_services": "Services",
        "total_parts": "Parts & materials",
        "total_labor": "Labor",
        "total_due": "Total amount due",
        "section_notes": "Technician Notes",
        "sig_customer": "Customer signature",
        "sig_authorized": "Authorized by",
        "footer_legal": (
            "This document is a record of work performed on the date stated above. "
            "Please retain for your vehicle service history."
        ),
        "footer_generated": "Generated by Workshop360",
        "part_fallback": "Part",
        "tel_prefix": "Tel",
    },
}

DOOR_STICKER: dict[str, dict[str, str]] = {
    "sq": {
        "title": "Etiketë Servisi",
        "service_complete": "Servis i Përfunduar",
        "date": "Data",
        "mileage": "KM",
        "next_service": "Servisi Tjetër",
        "tbd": "—",
    },
    "en": {
        "title": "Door Sticker",
        "service_complete": "Service Complete",
        "date": "Date",
        "mileage": "KM",
        "next_service": "Next Service",
        "tbd": "TBD",
    },
}

SERVICE_BOOKLET: dict[str, dict[str, str]] = {
    "sq": {
        "title": "Libër Digital i Servisit",
        "subtitle": "Historiku i Plotë i Servisit",
        "generated": "Gjeneruar",
        "vehicle_info": "Informacioni i Automjetit",
        "make_model": "Marka / Modeli",
        "owner": "Pronari",
        "vin": "VIN",
        "plate": "Targa",
        "year": "Viti",
        "odometer": "Kilometrazhi aktual",
        "service_history": "Historiku i Servisit",
        "visit": "Vizita",
        "status": "Statusi",
        "hour_meter": "Orëmotor",
        "performed_by": "Kryer nga",
        "services_performed": "Shërbimet e Kryera",
        "description": "Përshkrimi",
        "qty": "Sasi",
        "price": "Çmimi",
        "parts_used": "Pjesët e Përdorura",
        "labor": "Puna",
        "total": "Totali",
        "no_visits": "Nuk ka vizita të përfunduara të regjistruara.",
        "na": "—",
        "period_year": "Periudha: viti {year}",
        "period_all": "Periudha: i gjithë historiku",
        "summary_title": "Përmbledhje",
        "summary_visits": "Vizita të përfunduara",
        "summary_total": "Totali i punës së kryer",
        "section_inspection": "Inspektim 360°",
        "col_section": "Seksioni",
        "col_check": "Kontrolli",
        "col_result": "Rezultati",
        "visit_total": "Totali i vizitës",
        "notes": "Shënime",
        "item": "Artikulli",
        "hours": "Orë",
        "footer_legal": "Ky dokument përmbledh punën e kryer për automjetin e mësipërm.",
    },
    "en": {
        "title": "Digital Service Booklet",
        "subtitle": "Complete Service History",
        "generated": "Generated",
        "vehicle_info": "Vehicle Information",
        "make_model": "Make / Model",
        "owner": "Owner",
        "vin": "VIN",
        "plate": "License Plate",
        "year": "Year",
        "odometer": "Current Odometer",
        "service_history": "Service History",
        "visit": "Visit",
        "status": "Status",
        "hour_meter": "Hour Meter",
        "performed_by": "Performed By",
        "services_performed": "Services Performed",
        "description": "Description",
        "qty": "Qty",
        "price": "Price",
        "parts_used": "Parts Used",
        "labor": "Labor",
        "total": "Total",
        "no_visits": "No completed visits recorded.",
        "na": "N/A",
        "period_year": "Period: calendar year {year}",
        "period_all": "Period: complete history",
        "summary_title": "Summary",
        "summary_visits": "Completed visits",
        "summary_total": "Total work performed",
        "section_inspection": "360° Inspection",
        "col_section": "Section",
        "col_check": "Check",
        "col_result": "Result",
        "visit_total": "Visit total",
        "notes": "Notes",
        "item": "Item",
        "hours": "Hours",
        "footer_legal": "This document summarizes completed work performed on the vehicle above.",
    },
}

API_ERRORS: dict[str, dict[str, str]] = {
    "sq": {
        "visit_not_found": "Vizita nuk u gjet.",
        "vehicle_not_found": "Automjeti nuk u gjet.",
        "report_completed_only": "Raporti i servisit është i disponueshëm vetëm për vizita të përfunduara.",
        "invalid_year": "Viti i pavlefshëm. Përdorni një vit kalendarik (p.sh. 2025) ose \"all\".",
    },
    "en": {
        "visit_not_found": "Visit not found.",
        "vehicle_not_found": "Vehicle not found.",
        "report_completed_only": "Service report is only available for completed visits.",
        "invalid_year": "Invalid year. Use a calendar year (e.g. 2025) or \"all\".",
    },
}


def get_labels(bundle: dict[str, dict[str, str]], language: str | None) -> dict[str, str]:
    lang = normalize_language(language)
    return bundle.get(lang, bundle["sq"])


def api_error(key: str, language: str | None) -> str:
    labels = get_labels(API_ERRORS, language)
    return labels.get(key, key)
