# Generated by Django 5.2.13 on 2026-04-28 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('default_duration_hours', models.DecimalField(decimal_places=2, default=1.0, help_text='Typical duration of this service in hours.', max_digits=5)),
                ('default_price', models.DecimalField(decimal_places=2, default=0, help_text='Typical base price for this service (labor only).', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PreventiveMaintenancePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name of the maintenance plan (e.g. 'Engine oil & filter').", max_length=255)),
                ('interval_km', models.PositiveIntegerField(blank=True, help_text='Kilometer interval between services (leave empty if not km-based).', null=True)),
                ('interval_hours', models.PositiveIntegerField(blank=True, help_text='Engine hours interval between services.', null=True)),
                ('interval_days', models.PositiveIntegerField(blank=True, help_text='Calendar days between services.', null=True)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('last_mileage_km', models.PositiveIntegerField(blank=True, null=True)),
                ('last_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plans', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VisitLaborLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_lines', to='vehicles.servicevisit')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VisitMaterialLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=7)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_materials', to='inventory.inventoryitem')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_lines', to='vehicles.servicevisit')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VisitServiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='Human-readable description shown on reports/invoices.', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=7)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_lines', to='visits.servicecatalogitem')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_lines', to='vehicles.servicevisit')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
