# Generated by Django 5.2.14 on 2026-05-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='global_vehicle_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Link to the platform-wide GlobalVehicle record (public schema).', null=True),
        ),
    ]
