# Generated by Django 5.2.14 on 2026-05-29 12:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('vehicles', '0008_vehicle_odometer_optional_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Workshop client record. Optional until linked after paperwork check.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='clients.client'),
        ),
        migrations.CreateModel(
            name='VehicleGalleryPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='vehicle_photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_vehicle_photos', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle gallery photo',
                'verbose_name_plural': 'Vehicle gallery photos',
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['vehicle', 'sort_order'], name='vehicles_ve_vehicle_f9d811_idx')],
            },
        ),
    ]
