# Generated by Django 5.2.14 on 2026-05-28 12:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0003_alter_workshoptenant_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalOwner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='global_owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Global owner',
                'verbose_name_plural': 'Global owners',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GlobalVehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vin', models.CharField(db_index=True, max_length=64, unique=True)),
                ('license_plate', models.CharField(db_index=True, max_length=32)),
                ('make', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('year', models.PositiveIntegerField()),
                ('engine_type', models.CharField(blank=True, max_length=64)),
                ('fuel_type', models.CharField(blank=True, max_length=32)),
                ('odometer_km', models.PositiveIntegerField(default=0)),
                ('hour_meter', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='global_vehicle_photos/')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive vehicles are archived but retained for history linking.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_global_vehicles', to=settings.AUTH_USER_MODEL)),
                ('registered_by_tenant', models.ForeignKey(blank=True, help_text='Workshop that first registered this VIN in the global registry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_global_vehicles', to='tenancy.workshoptenant')),
            ],
            options={
                'verbose_name': 'Global vehicle',
                'verbose_name_plural': 'Global vehicles',
                'ordering': ['license_plate'],
            },
        ),
        migrations.CreateModel(
            name='VehicleClaimToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('owner_claim', 'Owner claim'), ('ownership_transfer', 'Ownership transfer')], max_length=32)),
                ('documents_verified', models.BooleanField(default=False, help_text='Mechanic confirmed identity documents for transfers.')),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_claim_tokens', to=settings.AUTH_USER_MODEL)),
                ('created_by_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_claim_tokens', to='tenancy.workshoptenant')),
                ('from_owner', models.ForeignKey(blank=True, help_text='Current owner for ownership transfers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_claim_tokens', to='global_vehicles.globalowner')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_claim_tokens', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_tokens', to='global_vehicles.globalvehicle')),
            ],
            options={
                'verbose_name': 'Vehicle claim token',
                'verbose_name_plural': 'Vehicle claim tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleOwnership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('claim_method', models.CharField(blank=True, help_text='How ownership was established (qr_claim, transfer, etc.).', max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_ownerships', to='global_vehicles.globalowner')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='global_vehicles.globalvehicle')),
            ],
            options={
                'verbose_name': 'Vehicle ownership',
                'verbose_name_plural': 'Vehicle ownerships',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AddIndex(
            model_name='globalvehicle',
            index=models.Index(fields=['make', 'model'], name='global_vehi_make_1bed1f_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicleownership',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('vehicle',), name='unique_active_vehicle_ownership'),
        ),
    ]
