# Generated by Django 5.2.14 on 2026-05-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleclaimtoken',
            name='new_license_plate',
            field=models.CharField(blank=True, help_text='Registration plate assigned to the new owner (required for transfers in XK/AL).', max_length=32),
        ),
        migrations.AddField(
            model_name='vehicleownership',
            name='license_plate',
            field=models.CharField(blank=True, help_text='Registration plate while this owner held the vehicle.', max_length=32),
        ),
        migrations.AlterField(
            model_name='globalvehicle',
            name='license_plate',
            field=models.CharField(db_index=True, help_text='Current registration plate. In XK/AL this often changes with each owner.', max_length=32),
        ),
        migrations.AlterField(
            model_name='globalvehicle',
            name='vin',
            field=models.CharField(db_index=True, help_text='Immutable vehicle identity — does not change when registration plate changes.', max_length=64, unique=True),
        ),
    ]
