# Generated by Django 5.2.14 on 2026-05-29 08:10

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_vehicles', '0002_vehicleclaimtoken_new_license_plate_and_more'),
        ('tenancy', '0004_tenantonboardingapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnershipTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('initiated_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('initiated_user_agent', models.CharField(blank=True, max_length=512)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('confirmed_user_agent', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending QR confirmation'), ('confirmed', 'Confirmed'), ('expired', 'Expired before confirmation'), ('cancelled', 'Cancelled by initiator'), ('disputed', 'Disputed (frozen for review)'), ('reversed', 'Reversed by platform superadmin')], db_index=True, default='pending', max_length=16)),
                ('initiator_notes', models.TextField(blank=True)),
                ('superadmin_notes', models.TextField(blank=True)),
                ('documents_verified', models.BooleanField(default=False)),
                ('new_license_plate', models.CharField(blank=True, max_length=32)),
                ('claim_token', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transfer', to='global_vehicles.vehicleclaimtoken')),
                ('confirmed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_owner', models.ForeignKey(blank=True, help_text='May be null for a first-time claim of an unclaimed vehicle.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transfers', to='global_vehicles.globalowner')),
                ('initiated_by_tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_transfers', to='tenancy.workshoptenant')),
                ('initiated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_transfers', to=settings.AUTH_USER_MODEL)),
                ('reversed_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='global_vehicles.ownershiptransfer')),
                ('to_owner', models.ForeignKey(blank=True, help_text='Null until the receiving owner confirms via QR.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='global_vehicles.globalowner')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='global_vehicles.globalvehicle')),
            ],
            options={
                'verbose_name': 'Ownership transfer',
                'verbose_name_plural': 'Ownership transfers',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('transfer_fee_currency', models.CharField(default='EUR', max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform pricing',
                'verbose_name_plural': 'Platform pricing',
            },
        ),
        migrations.CreateModel(
            name='TransferBilling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_currency', models.CharField(default='EUR', max_length=3)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('processing', 'Processing'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('waived', 'Waived (superadmin)')], default='unpaid', max_length=16)),
                ('invoice_reference', models.CharField(blank=True, max_length=64)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_transfer_fees', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='billing', to='global_vehicles.ownershiptransfer')),
            ],
            options={
                'verbose_name': 'Transfer billing',
                'verbose_name_plural': 'Transfer billings',
            },
        ),
        migrations.CreateModel(
            name='VehicleAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_schema', models.CharField(db_index=True, max_length=63)),
                ('tenant_name', models.CharField(blank=True, max_length=255)),
                ('vehicle_tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('global_vehicle_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('entity', models.CharField(choices=[('vehicle', 'Vehicle'), ('ownership', 'Ownership'), ('registration', 'Registration'), ('photo', 'Photo'), ('assignment', 'Assignment'), ('archive', 'Archive'), ('billing', 'Billing')], db_index=True, max_length=16)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('archived', 'Archived'), ('restored', 'Restored'), ('transfer_initiated', 'Transfer initiated'), ('transfer_confirmed', 'Transfer confirmed'), ('transfer_cancelled', 'Transfer cancelled'), ('transfer_expired', 'Transfer expired'), ('transfer_disputed', 'Transfer disputed'), ('transfer_reversed', 'Transfer reversed'), ('claimed', 'Owner claimed'), ('billing_changed', 'Billing changed')], db_index=True, max_length=24)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('actor_user_id', models.UUIDField(blank=True, null=True)),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('actor_role', models.CharField(blank=True, max_length=32)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request_user_agent', models.CharField(blank=True, max_length=512)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, max_length=512)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Vehicle audit event',
                'verbose_name_plural': 'Vehicle audit events',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['tenant_schema', 'vehicle_tenant_id'], name='global_vehi_tenant__182ef3_idx'), models.Index(fields=['global_vehicle_id', 'occurred_at'], name='global_vehi_global__3cd5f5_idx'), models.Index(fields=['entity', 'action'], name='global_vehi_entity_af5e63_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ownershiptransfer',
            index=models.Index(fields=['vehicle', '-initiated_at'], name='global_vehi_vehicle_7d5d6c_idx'),
        ),
        migrations.AddIndex(
            model_name='ownershiptransfer',
            index=models.Index(fields=['from_owner', 'to_owner'], name='global_vehi_from_ow_f1fb08_idx'),
        ),
        migrations.AddIndex(
            model_name='ownershiptransfer',
            index=models.Index(fields=['status', 'initiated_at'], name='global_vehi_status_4b2f0d_idx'),
        ),
    ]
