# Generated by Django 5.2.14 on 2026-05-29 15:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_vehicles', '0003_ownershiptransfer_tenantplatformbilling_and_more'),
        ('tenancy', '0004_tenantonboardingapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalVehiclePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='vehicle_photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_global_vehicle_photos', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by_tenant', models.ForeignKey(blank=True, help_text='Workshop that posted the photo. Used to gate edits / deletes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_vehicle_photos', to='tenancy.workshoptenant')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='global_vehicles.globalvehicle')),
            ],
            options={
                'verbose_name': 'Global vehicle photo',
                'verbose_name_plural': 'Global vehicle photos',
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['vehicle', 'sort_order'], name='global_vehi_vehicle_0e6d3d_idx'), models.Index(fields=['uploaded_by_tenant'], name='global_vehi_uploade_9c9ab1_idx')],
            },
        ),
    ]
