# Generated by Django 5.2.14 on 2026-05-30 20:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_vehicles', '0006_preventivemaintenanceorder'),
        ('tenancy', '0004_tenantonboardingapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('kind', models.CharField(choices=[('subscription', 'Subscription'), ('transfer', 'Ownership transfer'), ('registration', 'Vehicle registration'), ('manual', 'Manual')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('processing', 'Processing'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('waived', 'Waived (superadmin)')], default='unpaid', max_length=16)),
                ('invoice_reference', models.CharField(blank=True, help_text='External payment reference (bank transfer id, Stripe invoice, etc.).', max_length=64)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('line_items', models.JSONField(blank=True, default=list)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_platform_invoices', to=settings.AUTH_USER_MODEL)),
                ('related_registration_charge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_invoice', to='global_vehicles.vehicleregistrationcharge')),
                ('related_transfer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_invoice', to='global_vehicles.transferbilling')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_invoices', to='tenancy.workshoptenant')),
            ],
            options={
                'verbose_name': 'Platform invoice',
                'verbose_name_plural': 'Platform invoices',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['tenant', '-issued_at'], name='global_vehi_tenant__3e883e_idx'), models.Index(fields=['payment_status'], name='global_vehi_payment_2ab6f8_idx'), models.Index(fields=['kind'], name='global_vehi_kind_0d568f_idx')],
            },
        ),
    ]
