# Generated by Django 5.2.14 on 2026-05-30 21:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_vehicles', '0007_platform_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformInvoiceReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('invoice_issued', 'Invoice issued'), ('due_7d', '7 days before due'), ('due_1d', '1 day before due'), ('period_end_7d', '7 days before period end'), ('period_end_1d', '1 day before period end'), ('overdue_final', 'Final overdue warning'), ('tenant_deactivated', 'Tenant deactivated')], max_length=32)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='global_vehicles.platforminvoice')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('invoice', 'kind'), name='unique_platform_invoice_reminder')],
            },
        ),
    ]
