# Generated by Django — platform issuer profile singleton

import decimal

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("global_vehicles", "0008_platform_invoice_reminder"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformIssuerProfile",
            fields=[
                (
                    "singleton_id",
                    models.PositiveSmallIntegerField(
                        default=1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=255)),
                (
                    "trade_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional trading name (e.g. Workshop360) shown on invoices.",
                        max_length=255,
                    ),
                ),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=128)),
                ("postal_code", models.CharField(blank=True, max_length=32)),
                ("country", models.CharField(blank=True, default="Albania", max_length=64)),
                ("vat_number", models.CharField(blank=True, max_length=64)),
                (
                    "company_registration_number",
                    models.CharField(
                        blank=True,
                        help_text="Business / company registration (e.g. NIPT).",
                        max_length=64,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=64)),
                ("website", models.URLField(blank=True)),
                ("bank_name", models.CharField(blank=True, max_length=128)),
                ("iban", models.CharField(blank=True, max_length=64)),
                (
                    "vat_rate_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=decimal.Decimal("0.00"),
                        help_text="VAT rate applied on subscription invoices (0 = no VAT line).",
                        max_digits=5,
                    ),
                ),
                (
                    "amounts_include_vat",
                    models.BooleanField(
                        default=True,
                        help_text="When true, invoice amounts include VAT; PDF shows net + VAT breakdown.",
                    ),
                ),
                (
                    "invoice_footer",
                    models.TextField(
                        blank=True,
                        help_text="Optional footer text on PDF invoices (payment terms, legal note).",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name="updated_platform_issuer_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform issuer profile",
                "verbose_name_plural": "Platform issuer profile",
            },
        ),
        migrations.AddConstraint(
            model_name="platformissuerprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("singleton_id", 1)),
                name="platform_issuer_singleton",
            ),
        ),
    ]
