# Generated by Django 5.2.14 on 2026-05-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='global_owner_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Link to the platform-wide GlobalOwner (public schema).', null=True, unique=True),
        ),
    ]
