# Generated by Django 5.2.14 on 2026-05-29 12:48

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('tenancy', '0004_tenantonboardingapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketplacelisting',
            options={'ordering': ['-created_at'], 'verbose_name': 'Marketplace listing (legacy)'},
        ),
        migrations.CreateModel(
            name='MarketplaceSeller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seller_type', models.CharField(choices=[('workshop', 'Workshop'), ('parts_shop', 'Parts shop'), ('individual', 'Individual')], max_length=20)),
                ('business_name', models.CharField(max_length=255)),
                ('location_city', models.CharField(blank=True, max_length=128)),
                ('location_country', models.CharField(default='XK', max_length=64)),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('membership_plan', models.CharField(default='free', max_length=32)),
                ('billing_status', models.CharField(default='active', max_length=16)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('contact_whatsapp', models.CharField(blank=True, max_length=32)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_marketplace_sellers', to=settings.AUTH_USER_MODEL)),
                ('contact_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_seller_accounts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Set when seller is a workshop on the platform.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_seller_profiles', to='tenancy.workshoptenant')),
            ],
            options={
                'verbose_name': 'Marketplace seller',
                'verbose_name_plural': 'Marketplace sellers',
            },
        ),
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='marketplace.partcategory')),
            ],
            options={
                'verbose_name': 'Part category',
                'verbose_name_plural': 'Part categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_number', models.CharField(blank=True, db_index=True, max_length=64)),
                ('oem_number', models.CharField(blank=True, db_index=True, max_length=64)),
                ('alternative_numbers', models.JSONField(blank=True, default=list)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished'), ('oem_takeoff', 'OEM take-off')], default='new', max_length=16)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_reason', models.CharField(blank=True, max_length=255)),
                ('is_promoted', models.BooleanField(default=False)),
                ('promoted_until', models.DateTimeField(blank=True, null=True)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('location_city_override', models.CharField(blank=True, max_length=128)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('contact_requests', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketplace.partcategory')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='marketplace.marketplaceseller')),
            ],
            options={
                'verbose_name': 'Spare part',
                'verbose_name_plural': 'Spare parts',
                'ordering': ['-is_promoted', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleCompatibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('make', models.CharField(db_index=True, max_length=64)),
                ('model', models.CharField(db_index=True, max_length=64)),
                ('year_from', models.PositiveIntegerField()),
                ('year_to', models.PositiveIntegerField()),
                ('engine', models.CharField(blank=True, max_length=64)),
                ('trim', models.CharField(blank=True, max_length=64)),
                ('compatibility_source', models.CharField(choices=[('tecdoc', 'TecDoc'), ('carapi', 'CarAPI'), ('manual', 'Manual'), ('seller', 'Seller-entered'), ('inferred', 'Inferred')], default='seller', max_length=16)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='marketplace.sparepart')),
            ],
            options={
                'verbose_name': 'Vehicle compatibility',
                'verbose_name_plural': 'Vehicle compatibilities',
            },
        ),
        migrations.CreateModel(
            name='VehicleIssue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('mapped_categories', models.ManyToManyField(blank=True, related_name='issues', to='marketplace.partcategory')),
            ],
            options={
                'verbose_name': 'Vehicle issue',
                'verbose_name_plural': 'Vehicle issues',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceBannerEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mechanic_tenant_schema', models.CharField(db_index=True, max_length=63)),
                ('mechanic_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('vehicle_tenant_id', models.UUIDField(blank=True, null=True)),
                ('global_vehicle_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('displayed_part_ids', models.JSONField(blank=True, default=list)),
                ('clicked_part_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('contact_clicked', models.BooleanField(default=False)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.vehicleissue')),
            ],
            options={
                'verbose_name': 'Marketplace banner event',
                'verbose_name_plural': 'Marketplace banner events',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='marketplaceseller',
            index=models.Index(fields=['seller_type', 'is_approved'], name='marketplace_seller__a8f7fd_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceseller',
            index=models.Index(fields=['tenant'], name='marketplace_tenant__3cbb41_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceseller',
            index=models.Index(fields=['location_country', 'location_city'], name='marketplace_locatio_c147f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceseller',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('tenant',), name='unique_workshop_seller_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='partcategory',
            index=models.Index(fields=['parent'], name='marketplace_parent__bf3cfe_idx'),
        ),
        migrations.AddIndex(
            model_name='sparepart',
            index=models.Index(fields=['category', 'is_active'], name='marketplace_categor_b530a3_idx'),
        ),
        migrations.AddIndex(
            model_name='sparepart',
            index=models.Index(fields=['seller', 'is_active'], name='marketplace_seller__f721ae_idx'),
        ),
        migrations.AddIndex(
            model_name='sparepart',
            index=models.Index(fields=['part_number'], name='marketplace_part_nu_5bb091_idx'),
        ),
        migrations.AddIndex(
            model_name='sparepart',
            index=models.Index(fields=['oem_number'], name='marketplace_oem_num_c73751_idx'),
        ),
        migrations.AddIndex(
            model_name='sparepart',
            index=django.contrib.postgres.indexes.GinIndex(fields=['alternative_numbers'], name='marketplace_alterna_ab59bd_gin'),
        ),
        migrations.AddIndex(
            model_name='vehiclecompatibility',
            index=models.Index(fields=['make', 'model', 'year_from', 'year_to'], name='marketplace_make_af3e23_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclecompatibility',
            unique_together={('spare_part', 'make', 'model', 'year_from', 'year_to', 'engine', 'trim')},
        ),
        migrations.AddIndex(
            model_name='marketplacebannerevent',
            index=models.Index(fields=['mechanic_tenant_schema', '-occurred_at'], name='marketplace_mechani_f63460_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacebannerevent',
            index=models.Index(fields=['clicked_part_id'], name='marketplace_clicked_09d97f_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacebannerevent',
            index=models.Index(fields=['issue', '-occurred_at'], name='marketplace_issue_i_6d13ac_idx'),
        ),
    ]
