# Generated by Django 5.2.13 on 2026-05-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoptenant',
            name='currency',
            field=models.CharField(default='EUR', help_text='ISO 4217 currency code', max_length=3),
        ),
        migrations.AddField(
            model_name='workshoptenant',
            name='language',
            field=models.CharField(default='en', help_text='ISO 639-1 language code', max_length=10),
        ),
    ]
