# Generated by Django 5.2.14 on 2026-05-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_add_tenant_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshoptenant',
            name='language',
            field=models.CharField(default='sq', help_text='ISO 639-1 language code', max_length=10),
        ),
    ]
